channels:
  - conda-forge
  
dependencies:
  - python=3.9.13             # https://pyreadiness.org/3.9/ 
  - pip=22.3                  # https://pip.pypa.io/en/stable/news/
  - pip:
    - rpaframework==19.0.0    # https://rpaframework.org/releasenotes.html
